<template id="index">
   <!--eslint-disable-->
    <div class="container principal">
        <!--<img src="../_imagens/letreca/letreca2.jpg" class="img-fluid im" alt="Imagem responsiva">-->
        <a class="btn play" href="/#/contextos" role="button"></a>
        <a class="btn config" href="/#/login" role="button"></a>
        
        <div id="links-fixos" class="pulsate-fwd btt" style="padding:5px; position:fixed; bottom: 1rem;" >
          <a href="/#/info" >
            <img class="icon heartbeat" src="../_imagens/letreca/info.png" style="width: 5%; top: 1.10rem; position: fixed;">
          </a>
        </div>
    </div>
</template>

<script>
/* eslint-disable */
import axios from "axios";

export default {
  template: "#index",
  data() {
    return {
      email: "",
      senha: ""
    };
  },

  methods: {
    checkform: function(e) {
      let payload = {
        email: this.email,
        senha: this.senha
      };

      axios.post("https://app.sisalfa.dcx.ufpb.br/letreca/v1/login", payload).then(response => {
        let token = response.data.token;
        window.localStorage.setItem("token", token);
        alert("Você está logado");
      });
      e.preventDefault();
    },

    ver: function(categoria) {
      this.$router.push("/teste/");
    },

  }
};
</script>

<style>
/* eslint-disable */
.container{
	position: relative;
	border: 2px solid;
	border-color: #A8D500;
	border-radius: 1%;
	box-shadow: 5px 5px;
	background-color: #A8D500;
  height: 650px;
}

.principal{
  background-image: url(../_imagens/letreca/letreca2.jpg);
  background-position: center;
  background-repeat: no-repeat;
  background-size: 85%;
}

.play{
	background-image: url(../_imagens/letreca/play1.png);
	background-position: center;
    background-repeat: no-repeat;
    background-size: 100%;
	position: absolute;
	left: 38%;
	top: 70%;
	border: none;
	height: 10%;
	width: 10%;
	background-color: #2196f3 !important;
}

.config{
	background-image: url(../_imagens/letreca/config.png);
	background-position: center;
  background-repeat: no-repeat;
  background-size: 85%;
	position: absolute;
	left: 50%;
	top: 70%;
	height: 10%;
	width: 10%;
	background-color: #267cb5 !important;
}

.im{
	position: relative;
	left: 0%;
}

.heartbeat {
	-webkit-animation: heartbeat 1.5s ease-in-out infinite both;
	animation: heartbeat 1.5s ease-in-out infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-9-16 19:56:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}

@media (max-width: 574px){
  .play{
    left: 35%;
    top: 65%;
    height: 10%;
    width: 15%;
  }
  .config{
    left: 52%;
    top: 65%;
    height: 10%;
    width: 15%;
  }
   .icon{
      width: 10% !important;
      left: 15px;
    }
    .btt{
      width: 2rem;
    }
}

@media (min-width: 576px) {
  .container {
    max-width: 700px !important;
  }
}

@media (min-width: 700px) {
  .container{
      max-width: 700px !important;
  }
}

@media (min-width: 768px) {
  .container{
      max-width: 768px !important;
  }
}

@media (max-width: 499px){
  .play{
    left: 35%;
    top: 63%;
    height: 10%;
    width: 15%;
  }
  .config{
    left: 52%;
    top: 63%;
    height: 10%;
    width: 15%;
  }
  .icon{
    width: 15% !important;
    left: 15px;
  }
  .btt{
    width: 2rem;
  }
}

@media (max-width: 360px){
  .play{
    left: 35%;
    top: 60%;
    height: 6%;
    width: 15%;
  }
  .config{
    left: 52%;
    top: 60%;
    height: 6%;
    width: 15%;
  }
   .icon{
    width: 15% !important;
    left: 15px;
  }
  .btt{
    width: 2rem;
  }
}

</style>
